server:
  port: 8989
  servlet:
    context-path: /springboot_day2
    jsp:
      init-parameters:
        development: true #开启jsp页面开发模式 作用: 修改jsp页面无需重启springboot应用


#声明基本属性注入值
name: 小陈
age: 23
price: 23.23
birthday: 2012/12/12 12:12:12 #注意:默认的日期格式为 yyyy/mm/dd HH:MM:ss
sex: true
qqs: 6099,7088,8009 #注入数组时候,多个元素用 "," 逗号隔开
lists: xiaoming,xiaochen,xiaosun,xiaohong  #注入list时候,多个元素用 "," 逗号隔开  和数组一致
maps: "{'aa':'小胡','bb':'小张'}"  #注入map集合可以使用 json形式进行注入  注意:使用@Value注入时必须加入 "#{${属性}}" 进行注入

#声明对象方式注入

#ali key
alipay:
  key:    xxxxx
  secrect:  xxxx

orders:
  id: 22
  name: xiaoming
  price: 23.23
# 配置jsp视图前缀和后缀  解析结果: 前缀+ controller返回值+后缀
spring:
  mvc:
    view:
      prefix: /  #视图前缀
      suffix: .jsp #视图后缀
